#!/usr/bin/env bash

# Swap's Manager
# Lane Maynor

swapdir="$HOME/.local/state/nvim-vim-pack/swap"

usage() {
	local exit_status=0
	if [[ "$1" == "fail" ]]; then
		exit_status=1
	fi
	echo "Usage: swaps [-h] [-d file]"
	echo "  -h            Display help"
	echo "  -d file       Delete file"
	exit "$exit_status"
}

default_swaps() {
	ls "$swapdir"
}

del_swap() {
	local file="$1"
	files=$(find "$swapdir" -type f -iname "*${file}*")

	if [[ -z "$files" ]]; then
		echo "No files have the name $file"
		exit 1
	else
		local files_deleted=0
		mapfile -t matches <<< "$files"
		local count="${#matches[@]}"

		if (( count == 1 )); then
			echo "Found $count file."
		else
			echo "Found $count files."
		fi

		for file in "${matches[@]}"; do
			echo "$file"
			read -r -p "Delete this file? (y/N): " response
			case "$response" in
				[yY][eE][sS]|[yY])
					rm "$file"
					((files_deleted++))
					;;
				*)
					echo "Canceled"
					continue
					;;
			esac
		done
		if (( files_deleted > 0 )); then
			if (( files_deleted == 1)); then
				echo "Deleted $files_deleted file."
			else
				echo "Deleted $files_deleted files."
			fi
		fi
		exit 0
	fi
}

swaps() {

	if [ $# -eq 0 ]; then
		default_swaps 
	fi

	while getopts ":hd:" opt; do
		case "${opt}" in
			h)
				usage; ;;
			d)
				del_swap "${OPTARG}"
				;;
			\?)
				echo "Invalid option: -${OPTARG}" >&2
				usage "fail"
				;;
			:)
				echo "Option -${OPTARG} requires a file name"
				exit 1
				;;
		esac
	done
}

swaps "$@"
